services:
  db:
    image: postgres:15-alpine
    container_name: si_portfolio_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: si_user
      POSTGRES_PASSWORD: si_password_segura
      POSTGRES_DB: si_portfolio
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: si_portfolio_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://si_user:si_password_segura@db/si_portfolio
      NB_DATA_PATH: /data/SMSSpamCollection.csv
      PYTHONUNBUFFERED: "1"
    volumes:
      - .:/app
      - ./data:/data
      - ./saved_models:/app/saved_models
    ports:
      - "8000:8000"

volumes:
  pgdata:
