name: si-backend
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - pip
  - pillow

  - pip:
    - fastapi
    - uvicorn
    - pydantic
    - sqlalchemy[asyncio]
    - asyncpg
    - alembic
    - tensorflow
    - tensorflow-datasets
    - python-multipart
