name: si-backend
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.13
  - pandas
  - numpy
  - scikit-learn
  - requests
  - pip

  - pip:
    - fastapi
    - uvicorn
    - pydantic
    - sqlalchemy[asyncio]
    - asyncpg
    - alembic
